export enum StateTokenType {
    EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
    PASSWORD_RESET = 'PASSWORD_RESET',
    EMAIL_UPDATE = 'EMAIL_UPDATE',
    MULTI_FACTOR_AUTH = 'MULTI_FACTOR_AUTH',
    OTP = 'OTP'
}
  
